f = open('another.txt','w')
f.write("I am writting")
f.close()

f = open("this.txt", "w")
f.write("this is nice\n")
f.write("this is bad\n")
f.write("this is woow\n")
f.write("this is f**\n")
f.close()